/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfas;

import com.mycompany.tallerpoo.AdmisionDeEmergencia;
import com.mycompany.tallerpoo.AsignacionBox;
import com.mycompany.tallerpoo.Box;
import com.mycompany.tallerpoo.DatosTaller;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class BoxDisponibles extends javax.swing.JFrame {

    /**
     * Creates new form BoxDisponibles
     */
    private static String box_update;
    DefaultTableModel tabla = new DefaultTableModel(); 
    
    public BoxDisponibles(AdmisionDeEmergencia admi) {
        initComponents();
        String[] titulo = new String[]{"Box disponibles"};
        tabla.setColumnIdentifiers(titulo);
        tablaBox.setModel(tabla);
        tablaBox.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila = tablaBox.rowAtPoint(e.getPoint());
                int columna = 0;
                if (fila >= 0){
                    box_update = String.valueOf(tablaBox.getValueAt(fila, columna));
                    DatosTaller.getBoxes().getPorNumero(Integer.parseInt(box_update)).setOcupado(true);
                    admi.setBox(DatosTaller.getBoxes().getPorNumero(Integer.parseInt(box_update)));
                    AsignacionBox asignacion = new AsignacionBox(LocalDate.now(),LocalTime.now(),DatosTaller.getBoxes().getPorNumero(Integer.parseInt(box_update)),admi);
                    dispose();
                }
            }
        }
        ); 
    }
    
    private void agregar(Box box){
        Object[] fila = {box.getNumero()};
        tabla.addRow(fila);
    }
    
    private void llamar(){
        ArrayList<Box> boxes = DatosTaller.getBoxes().getBoxes();
        for(Box box : boxes){
            if(!box.isOcupado()){
            agregar(box);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBox = new javax.swing.JTable();
        actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Box disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBox);

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualizar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(actualizar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        llamar();
    }//GEN-LAST:event_actualizarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBox;
    // End of variables declaration//GEN-END:variables
}
