/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfas;

/**
 * Esta clase representa la interfaz de información administrativa en la aplicación.
 * Permite al usuario navegar entre diferentes categorías de información, como pacientes, funcionarios y otros datos.
 * El usuario puede acceder a la información de estas categorías seleccionando los botones correspondientes.
 * También tiene la opción de regresar al menú principal.
 * 
 * @author Santi
 */
public class InfoAdministrativa extends javax.swing.JFrame {

    /**
     * Constructor de la clase `InfoAdministrativa`. Inicializa la interfaz gráfica de usuario.
     */
    public InfoAdministrativa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanleInfoAdmin = new javax.swing.JPanel();
        jButtonPacientes = new javax.swing.JButton();
        jButtonFuncionarios = new javax.swing.JButton();
        jButtonOtros = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPacientes.setText("Pacientes");
        jButtonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacientesActionPerformed(evt);
            }
        });

        jButtonFuncionarios.setText("Funcionarios");
        jButtonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionariosActionPerformed(evt);
            }
        });

        jButtonOtros.setText("Otros");
        jButtonOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtrosActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("<< Atrás");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanleInfoAdminLayout = new javax.swing.GroupLayout(jPanleInfoAdmin);
        jPanleInfoAdmin.setLayout(jPanleInfoAdminLayout);
        jPanleInfoAdminLayout.setHorizontalGroup(
            jPanleInfoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleInfoAdminLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanleInfoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jButtonOtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(jPanleInfoAdminLayout.createSequentialGroup()
                .addComponent(jButtonAnterior)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanleInfoAdminLayout.setVerticalGroup(
            jPanleInfoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleInfoAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnterior)
                .addGap(38, 38, 38)
                .addComponent(jButtonPacientes)
                .addGap(18, 18, 18)
                .addComponent(jButtonFuncionarios)
                .addGap(18, 18, 18)
                .addComponent(jButtonOtros)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanleInfoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanleInfoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento cuando se hace clic en el botón "Atrás".
     * Abre la interfaz del menú de administrador de sistemas al presionar el botón "Atrás".
     * @param evt El evento de acción del botón.
     */
    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        PantallaAdminSist atras = new PantallaAdminSist();
        atras.setVisible(true);
        atras.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    /**
     * Maneja el evento cuando se hace clic en el botón "Pacientes".
     * Abre la interfaz que muestra la lista de pacientes al presionar el botón "Pacientes".
     * @param evt El evento de acción del botón.
     */
    private void jButtonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacientesActionPerformed
        TablaPacientes opcion1 = new TablaPacientes();
        opcion1.setVisible(true);
        opcion1.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonPacientesActionPerformed

     /**
     * Maneja el evento cuando se hace clic en el botón "Funcionarios".
     * Abre la interfaz que muestra la lista de funcionarios al presionar el botón "Funcionarios".
     * @param evt El evento de acción del botón.
     */
    private void jButtonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionariosActionPerformed
        TablaFuncionarios opcion2 = new TablaFuncionarios();
        opcion2.setVisible(true);
        opcion2.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonFuncionariosActionPerformed

    /**
     * Maneja el evento cuando se hace clic en el botón "Otros".
     * Abre la interfaz de "Otros" al presionar el botón "Otros".
     * @param evt El evento de acción del botón.
     */
    private void jButtonOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtrosActionPerformed
        Otros opcion3 = new Otros();
        opcion3.setVisible(true);
        opcion3.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButtonOtrosActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonOtros;
    private javax.swing.JButton jButtonPacientes;
    private javax.swing.JPanel jPanleInfoAdmin;
    // End of variables declaration//GEN-END:variables
}
