/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazUsuario;

/**
 * Esta clase representa la interfaz de usuario para el menú del gestor de centro del hospital.
 * Proporciona opciones para realizar diferentes consultas y cálculos relacionados con los pacientes y médicos del hospital.
 * Cada botón del menú dirige a una opción específica.
 * @author Matías
 */
public class MenuGestorCentro extends javax.swing.JFrame {

    /**
     * Constructor de la clase `MenuGestorCentro`. Inicializa la interfaz gráfica de usuario.
     */
    public MenuGestorCentro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonOpcion1 = new javax.swing.JButton();
        jButtonOpcion2 = new javax.swing.JButton();
        jButtonOpcion3 = new javax.swing.JButton();
        jButtonOpcion4 = new javax.swing.JButton();
        jButtonOpcion5 = new javax.swing.JButton();
        jButtonOpcion6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOpcion1.setText("1. Cantidad de pacientes atendidos por un médico en un rango de fechas");
        jButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion1ActionPerformed(evt);
            }
        });

        jButtonOpcion2.setText("2. Cantidad de pacientes atendidos en un rango de fechas y edades ");
        jButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion2ActionPerformed(evt);
            }
        });

        jButtonOpcion3.setText("3. Pacientes con más consultas en un rango de fechas");
        jButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion3ActionPerformed(evt);
            }
        });

        jButtonOpcion4.setText("4. Médicos/s que más pacientes haya atendido en un rango de fechas");
        jButtonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion4ActionPerformed(evt);
            }
        });

        jButtonOpcion5.setText("5. Triages realizados en un rango de fechas");
        jButtonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion5ActionPerformed(evt);
            }
        });

        jButtonOpcion6.setText("6. Cantidad de Triages que fueron cambiados ");
        jButtonOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButtonOpcion1)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpcion2)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpcion3)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpcion4)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpcion5)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpcion6)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento cuando se hace clic en el botón "1. Cantidad de pacientes atendidos por un médico en un rango de fechas".
     * Abre la interfaz de la opción 1.
     * @param evt El evento de acción del botón.
     */
    private void jButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion1ActionPerformed
        Op1GestorCentro opcion = new Op1GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion1ActionPerformed

    /**
     * Maneja el evento cuando se hace clic en el botón "2. Cantidad de pacientes atendidos en un rango de fechas y edades".
     * Abre la interfaz de la opción 2.
     * @param evt El evento de acción del botón.
     */
    private void jButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion2ActionPerformed
        Op2GestorCentro opcion = new Op2GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion2ActionPerformed

    /**
     * Maneja el evento cuando se hace clic en el botón "3. Pacientes con más consultas en un rango de fechas".
     * Abre la interfaz de la opción 3.
     * @param evt El evento de acción del botón.
     */
    private void jButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion3ActionPerformed
        Op3GestorCentro opcion = new Op3GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion3ActionPerformed
    
    /**
     * Maneja el evento cuando se hace clic en el botón "4. Médicos/s que más pacientes haya atendido en un rango de fechas".
     * Abre la interfaz de la opción 4.
     * @param evt El evento de acción del botón.
     */
    private void jButtonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion4ActionPerformed
        Op4GestorCentro opcion = new Op4GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion4ActionPerformed

    /**
     * Maneja el evento cuando se hace clic en el botón "5. Triages realizados en un rango de fechas".
     * Abre la interfaz de la opción 5.
     * @param evt El evento de acción del botón.
     */
    private void jButtonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion5ActionPerformed
        Op5GestorCentro opcion = new Op5GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion5ActionPerformed

    /**
     * Maneja el evento cuando se hace clic en el botón "6. Cantidad de Triages que fueron cambiados".
     * Abre la interfaz de la opción 6.
     * @param evt El evento de acción del botón.
     */
    private void jButtonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion6ActionPerformed
        Op6GestorCentro opcion = new Op6GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion6ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpcion1;
    private javax.swing.JButton jButtonOpcion2;
    private javax.swing.JButton jButtonOpcion3;
    private javax.swing.JButton jButtonOpcion4;
    private javax.swing.JButton jButtonOpcion5;
    private javax.swing.JButton jButtonOpcion6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
