/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;

import com.mycompany.tallerpoo.ListaPacientes;
import com.mycompany.tallerpoo.Paciente;
import com.mycompany.tallerpoo.RegistroMedico;
import static com.mycompany.tallerpoo.RegistroMedico.calcularMasConsPorFecha;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase representa la interfaz de usuario para realizar una operación
 * específica de un gestor centro del hospital. Proporciona la funcionalidad
 * para buscar el DNI de los pacientes con más consultas en un rango de fechas.
 * Los resultados se muestran en una tabla.
 *
 * @author Santi
 */
public class Op3GestorCentro extends javax.swing.JFrame {

    String barra = File.separator;
    /**
     * Creates new form Op3GestorCentro
     */
    String ubicacion = System.getProperty("user.dir") + barra + "Archivos"
            + barra + "Pacientes.txt";
    public static String pacienteUpdate;
    DefaultTableModel tabla = new DefaultTableModel();

    /**
     * Constructor de la clase Op3GestorCentro. Inicializa la interfaz gráfica
     * de usuario y la tabla.
     */
    public Op3GestorCentro() {
        initComponents();
        String[] titulo = new String[]{"Pacientes atendidos en el rango de fechas"};
        tabla.setColumnIdentifiers(titulo);
        jTableListaPacientes.setModel(tabla);
        jTableListaPacientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = jTableListaPacientes.rowAtPoint(e.getPoint());
                int columna = 2;
                if (fila > -1) {
                    pacienteUpdate = (String) jTableListaPacientes.getValueAt(
                            fila, columna);
                    //ListaPacientes registroMedico = new ListaPacientes();
                    //registroMedico.setVisible(true);
                }
            }
        }
        );
    }

    /**
     * Agrega una fila a la tabla con la lista de pacientes que han tenido más
     * consultas.
     *
     * @param paciente Un ArrayList de String que contiene información del
     * paciente.
     */
    private void agregar(ArrayList<Paciente> paciente) {
        try {
            if (paciente.size() > 0) {
                Object[] fila = new Object[paciente.size()]; // Crear un arreglo de objetos para la fila
                for (int i = 0; i < paciente.size(); i++) {
                    fila[i] = paciente.get(i); // Agregar los elementos a la fila
                }
                tabla.addRow(fila); // Agregar la fila a la tabla
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }

    /**
     * Realiza una búsqueda en función de las fechas ingresadas y muestra los
     * pacientes con más consultas en la tabla.
     *
     * @param a La fecha inicial para la búsqueda.
     * @param b La fecha final para la búsqueda.
     * @throws IOException Si ocurre un error de lectura o escritura de
     * archivos.
     */
    private void llamar(LocalDate a, LocalDate b) throws IOException {
        RegistroMedico lista = new RegistroMedico();
        ListaPacientes listaPacientes = new ListaPacientes();
        String userDir = System.getProperty("user.dir");
        listaPacientes.leer(userDir + "/Archivos/Pacientes.txt");
        ArrayList<String> pacientes = lista.calcularMasConsPorFecha(a, b);
        Paciente objeto = new Paciente();
        ArrayList<Paciente> array = new ArrayList<Paciente>();
        int dni;
        for (int i = 0; i < pacientes.size(); i++) {
            dni = Integer.parseInt(pacientes.get(i));
            objeto = listaPacientes.getPorDni(dni);
            array.add(objeto);
        }

        try {
            agregar(array);
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaPacientes = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        fecha11 = new javax.swing.JTextField();
        fecha2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la priemera fecha");

        jLabel2.setText("Ingrese la segunda fecha");

        jTableListaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Lista de pacientes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaPacientes);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        anterior.setText("<< Atrás");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        fecha11.setText("aaaa/mm/dd");

        fecha2.setText("aaaa/mm/dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha11))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha2))
                        .addGap(18, 18, 18)
                        .addComponent(buscar))
                    .addComponent(anterior))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(fecha11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de acción cuando se hace clic en el botón "Buscar".
     * Realiza la búsqueda en función de las fechas ingresadas y llama a
     * llamar() para mostrar los resultados.
     */
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String fechaUno = fecha11.getText();
        String fechaDos = fecha2.getText();
        if (validarFormatoFecha(fechaUno) && validarFormatoFecha(fechaDos)) {
            DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate primeraFecha = LocalDate.parse(fechaUno, formatter1);
            LocalDate segundaFecha = LocalDate.parse(fechaDos, formatter1);
            try {
                llamar(primeraFecha, segundaFecha);
            } catch (IOException ex) {
                Logger.getLogger(Op3GestorCentro.class.getName()).log(
                        Level.SEVERE,
                        null, ex);
            }
        } else {
            // Si las fechas no cumplen con el formato esperado, mostrar un mensaje de error.
            JOptionPane.showMessageDialog(this,
                    "Formato de fecha incorrecto. Utiliza yyyy/MM/dd.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * Valida el formato de una fecha ingresada.
     *
     * @param fecha La fecha a validar.
     * @return `true` si la fecha tiene el formato correcto, `false` en caso contrario.
     */
    private boolean validarFormatoFecha(String fecha) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate.parse(fecha, formatter);
            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }

    /**
     * Maneja el evento cuando se hace clic en el botón "Atrás". Muestra la
     * ventana anterior y cierra la actual.
     */
    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        MenuGestorCentro menu = new MenuGestorCentro();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_anteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField fecha11;
    private javax.swing.JTextField fecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaPacientes;
    // End of variables declaration//GEN-END:variables

    
}
