/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazUsuario;

import com.mycompany.tallerpoo.Triage;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * Esta clase representa la interfaz gráfica de usuario para la gestión de
 * registros de triaje.
 * Permite a los usuarios ver una lista de triaje.
 *
 * @author Santi
 */
public class Op6GestorCentro extends javax.swing.JFrame {

    String barra = File.separator;
    
    String ubicacion = System.getProperty("user.dir") + barra + "Archivos" + barra + "Triage.txt";
    public static String pacienteUpdate;
    DefaultTableModel tabla = new DefaultTableModel();
    
    /**
     * Constructor que inicializa una nueva ventana de Op6GestorCentro y sus componentes.
     */
    
    public Op6GestorCentro() {
        initComponents();
        String [] titulo =new String[]{"Triages"};
        tabla.setColumnIdentifiers(titulo);
        jTableTriage.setModel(tabla);
        jTableTriage.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila = jTableTriage.rowAtPoint(e.getPoint());
                int columna = 2; 
                if (fila > -1){
                    pacienteUpdate = (String) jTableTriage.getValueAt(fila,columna);
                    PantallaTriage triage = new PantallaTriage();
                    triage.setVisible(true);
                }
            }
        }
        );
        }
   
    /**
     * Agrega registros de triage a la tabla.
     *
     * @param triage lista de registros de triage a mostrar.
     */
    private void agregar(ArrayList<String> triage) {
        try {
            if (triage.size() > 0) {
                Object[] fila = new Object[triage.size()]; // Crear un arreglo de objetos para la fila
                for (int i = 0; i < triage.size(); i++){
                    fila[0] = triage.get(i); // Agregar los elementos a la fila
                    tabla.addRow(fila);// Agregar la fila a la tabla
                }
            }
           
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
    /**
     * Obtiene y muestra registros de triage cambiados dentro de un rango de 
     * fechas especificado.
     *
     * @param a La fecha de inicio del rango de fechas.
     * @param b La fecha de fin del rango de fechas.
     * @throws IOException Si ocurre un error de E/S al leer los datos de triage.
     */
    private void llamar(LocalDate a, LocalDate b) throws IOException {
        ArrayList<String> triages = Triage.obtenerTriageCambiadosPorFecha( a ,
                                                                            b);
        
        try {
 
                agregar(triages);
                   
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTriage = new javax.swing.JTable();
        actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableTriage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Triages"
            }
        ));
        jScrollPane1.setViewportView(jTableTriage);

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(actualizar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(actualizar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Actualiza  y muestra los datos de la tabla que contiene triages.
    *
    * @param evt El evento de acción.
    */
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        LocalDate primeraFecha = LocalDate.of(0001, 01, 01);
        LocalDate segundaFecha = LocalDate.of(2024, 01, 01);
        try {
            llamar(primeraFecha, segundaFecha);
        } catch (Exception ex) {
            Logger.getLogger(Op5GestorCentro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTriage;
    // End of variables declaration//GEN-END:variables
}
