
package InterfazUsuario;
import java.time.*;
import com.mycompany.tallerpoo.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lucas
 */
public class BuscarEstFecha extends javax.swing.JFrame {

    /**
     * Creates new form resetudio
     */
    public BuscarEstFecha() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDia = new javax.swing.JTextField();
        jMes = new javax.swing.JTextField();
        jAnio = new javax.swing.JTextField();
        jResEstudios = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaResul = new javax.swing.JTable();
        jLabelDia = new javax.swing.JLabel();
        jLabelMes = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JLabel();
        jLabelIngrese = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar estudios por fecha");
        setAlwaysOnTop(true);
        setResizable(false);

        jDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiaActionPerformed(evt);
            }
        });

        jResEstudios.setText("Obtener");
        jResEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResEstudiosActionPerformed(evt);
            }
        });

        jListaResul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {
                "Fecha", "Hora", "Tipo", "Informe", "Paciente"
            }
        ));
        jListaResul.setEnabled(false);
        jListaResul.getTableHeader().setReorderingAllowed(false);
        jListaResul.setUpdateSelectionOnSort(false);
        jListaResul.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jListaResul);

        jLabelDia.setText("Dia");
        jLabelDia.setAutoscrolls(true);

        jLabelMes.setText("Mes");
        jLabelMes.setAutoscrolls(true);

        jLabelAnio.setText("Año");
        jLabelAnio.setAutoscrolls(true);

        jLabelIngrese.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIngrese.setText("Ingrese una fecha");
        jLabelIngrese.setAutoscrolls(true);

        jLabelError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelError.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelDia)
                        .addGap(53, 53, 53)
                        .addComponent(jLabelMes)
                        .addGap(52, 52, 52)
                        .addComponent(jLabelAnio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jResEstudios)))
                .addGap(281, 281, 281))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabelIngrese))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIngrese)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDia)
                    .addComponent(jLabelMes)
                    .addComponent(jLabelAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jResEstudios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addContainerGap())
        );

        jLabelError.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDiaActionPerformed

    
    private void jResEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResEstudiosActionPerformed
        DefaultTableModel model= (DefaultTableModel) jListaResul.getModel();

        jLabelError.setText("");
        
        model.setRowCount(0);
        


        //jLabelError.setText("jLabel1");

        try{
            LocalDate fecha= LocalDate.of(Integer.parseInt(jAnio.getText()),
                                         Integer.parseInt(jMes.getText()),
                                     Integer.parseInt(jDia.getText()));
            System.out.println(jAnio.getText()+jMes.getText()+jDia.getText());
            
            ArrayList <ResultadoEstudios> listaCoin=DatosTaller.getResultados().getListaPorFecha(fecha);
           
            Paciente paci;
            System.out.println(listaCoin);

            for(int i=0;i<listaCoin.size();i++){
                paci=listaCoin.get(i).getPaciente();
                Object[] array={listaCoin.get(i).getFecha(),listaCoin.get(i).getHora(),listaCoin.get(i).getTipoDeEstudio(),
                    listaCoin.get(i).getInformeDeEstudio(), paci.getDocumento()};
                
                model.addRow(array);
            }
            
            if (listaCoin.isEmpty()){
                jLabelError.setText("No se encontraron resultados");
            }
            
        }
        catch (NullPointerException exc){
            System.out.println("null");
            
            jLabelError.setText("Complete todos los campos");
        }
        catch (DateTimeException exc){
            jLabelError.setText("Fecha inválida");
        }
        catch (NumberFormatException exc){
            jLabelError.setText("Fecha inválida");
        }
    }//GEN-LAST:event_jResEstudiosActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAnio;
    private javax.swing.JTextField jDia;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelIngrese;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JTable jListaResul;
    private javax.swing.JTextField jMes;
    private javax.swing.JButton jResEstudios;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
