/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

/**
 *
 * @author 54345
 */
public class MenuGestorCentroEliminar extends javax.swing.JFrame {

    /**
     * Creates new form MenuGestorCentro
     */
    public MenuGestorCentroEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonOpcion1 = new javax.swing.JButton();
        jButtonOpcion2 = new javax.swing.JButton();
        jButtonOpcion3 = new javax.swing.JButton();
        jButtonOpcion4 = new javax.swing.JButton();
        jButtonOpcion5 = new javax.swing.JButton();
        jButtonOpcion6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOpcion1.setText("Cantidad de pacientes atendidos por un médico en un rango de fechas");
        jButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion1ActionPerformed(evt);
            }
        });

        jButtonOpcion2.setText("Cantidad de pacientes atendidos en un rango de fechas y edades");
        jButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion2ActionPerformed(evt);
            }
        });

        jButtonOpcion3.setText("Pacientes con más consultas en un rango de fechas");
        jButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion3ActionPerformed(evt);
            }
        });

        jButtonOpcion4.setText("Médico/s que más pacientes haya/n atendido en un rango de fechas ");
        jButtonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion4ActionPerformed(evt);
            }
        });

        jButtonOpcion5.setText("Triages realizados en un rango de fechas");
        jButtonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion5ActionPerformed(evt);
            }
        });

        jButtonOpcion6.setText("Cantidad de triages que fueron cambiados");
        jButtonOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion5, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButtonOpcion6, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion1ActionPerformed
        Op1GestorCentroEliminar opcion = new Op1GestorCentroEliminar();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion1ActionPerformed

    private void jButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion2ActionPerformed
        Op2GestorCentroEliminar opcion = new Op2GestorCentroEliminar();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion2ActionPerformed

    private void jButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion3ActionPerformed
        Op3GestorCentro opcion = new Op3GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion3ActionPerformed

    private void jButtonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion4ActionPerformed
        Op4GestorCentro opcion = new Op4GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion4ActionPerformed

    private void jButtonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion5ActionPerformed
        Op5GestorCentro opcion = new Op5GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion5ActionPerformed

    private void jButtonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion6ActionPerformed
        Op6GestorCentro opcion = new Op6GestorCentro();
        opcion.setVisible(true);
        opcion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonOpcion6ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpcion1;
    private javax.swing.JButton jButtonOpcion2;
    private javax.swing.JButton jButtonOpcion3;
    private javax.swing.JButton jButtonOpcion4;
    private javax.swing.JButton jButtonOpcion5;
    private javax.swing.JButton jButtonOpcion6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
